spring:
  application:
    name: Backend
  devtools:
    livereload:
      enabled: false


  datasource:
    url: jdbc:postgresql://postgres:5432/ans_machine_db
    username: postgres
    password: p855060123d
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: redis
      port: 6379

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 50
        keep-alive: 30s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  main:
    allow-bean-definition-overriding: true


validation:
  file-upload:
    max-file-size: 10MB
    allowed-file-types:
      - "image/png"
      - "image/jpeg"
      - "application/pdf"

file-upload:
  location: /uploads
  clamav-host: localhost
  clamav-port: 3310

jwt:
  secret: "sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3"
  access-expiration: 100000
  refresh-expiration: 86400000

# Настройки чатов
chat:
  limits:
    max-messages-per-chat: 1000
    max-attachments-per-message: 5
    max-message-length: 1000
    max-chats-per-user: 10
    max-users-per-chat: 5
    message-rate-limit: 60
    attachment-max-size: 10MB
  lifetime:
    inactive-chat-close-time: PT24H
  status:
    active: ACTIVE
    closed: CLOSED
    pending: PENDING

# Настройки уведомлений
notification:
  interval: 5s
  templates:
    new-message: "Новое сообщение от %s: %s"
    operator-typing: "Оператор печатает..."

telegram:
  username: dialog_x_qanswer_bot
  token: 7520341907:AAFkCZPkx7d676-qwLMuAhfL4jaXWlU_Blg

vk:
  bot:
    token:
  group:
    id:
  api:
    version: 5.199

email:
  imap_host:
    yandex: "imap.yandex.com"
    gmail: "imap.gmail.com"
  imap_port: 993
  imap_ssl_enable: true
  imap_store: "imaps"
  imap_folder: "INBOX"

nlp:
  lemmatizer:
    implementation: external-api
    api-url: https://lindat.mff.cuni.cz/services/udpipe/api/process
    connectTimeoutMillis: 5000
    read-timeout-millis: 30000
  api:
    client:
      embedding-api-url: https://router.huggingface.co/hf-inference/pipeline/sentence-similarity/sentence-transformers/all-MiniLM-L6-v2
      apiKey: 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
      connection-timeout-millis: 5000
      read-timeout-millis: 30000
      max-batch-size: 50

answersearch:
  weights:
    similarity: 0.7
    trust: 0.3

ml:
  service:
    base-url: http://localhost:8000/generate
  prompts:
    correction-prompt-template: "Исправь орфографические, пунктуационные и грамматические ошибки в следующем предложении, строго соблюдая нормы современного русского языка. Дай только исправленный вариант без пояснений: %s"
    rewrite-instruction-template: "Перепиши следующий корпоративный ответ, сделав его более дружелюбным, теплым и естественным, но при этом не перегруженным деталями. Сделай так, чтобы ответ звучал приветливо и было ощущение личного общения. Также убедись, что ответ остается коротким и по делу."
    rewrite-prompt-template: "%sШаблонный ответ: %s. Дай только измененный вариант."
  params:
    temperature: 0.7
    max-new-tokens: 150
    top-p: 0.95
    do-sample: false
    stream: false
    max-retries: 3
websocket:
  endpoint: /ws
  allowed-origins: "http://localhost:8080"
  heartbeat:
    interval: 30000 # Интервал отправки heartbeat (пингов) от сервера клиенту (мс)
    timeout: 10000  # Время ожидания ответа на пинг перед разрывом соединения (мс)
  message:
    buffer-size: 16384 # Размер буфера входящих сообщений (байты)
    send-timeout: 3000 # Таймаут отправки сообщения (мс)
  stomp:
    simple-broker:
      enabled: true
      destination-prefix: /topic/,/queue/
      application-destination-prefix: /app
      user-destination-prefix: /user
subscription:
  price: 790






