spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ans_machine_db
    username: postgres
    password: nikita090504
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  websocket:
    endpoint: /test_endpoint_ans
    allowed-origin-patterns: "*"
    application-destination-prefix: /app
    user-destination-prefix: /user


validation:
  file-upload:
    max-file-size: 10MB
    allowed-file-types:
      - "image/png"
      - "image/jpeg"
      - "application/pdf"

file-upload:
  location: /uploads
  clamav-host: localhost
  clamav-port: 3310

# Настройки чатов
chat:
  limits:
    max-messages-per-chat: 1000
    max-attachments-per-message: 5
  lifetime:
    inactive-chat-close-time: 24h
  status:
    active: ACTIVE
    closed: CLOSED
    pending: PENDING

# Настройки уведомлений
notification:
  interval: 5s
  templates:
    new-message: "Новое сообщение от %s: %s"
    operator-typing: "Оператор печатает..."

