spring:
  application:
    name: Backend
  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/ans_machine_db
    username: postgres
    password: p855060123d
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: redis
      port: 6379

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 50
        keep-alive: 30s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: "sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3"
  access-expiration: 100000
  refresh-expiration: 86400000
  isLocal: false

email:
  imap_host:
    yandex: "imap.yandex.com"
    gmail: "imap.gmail.com"
  imap_port: 993
  imap_ssl_enable: true
  imap_store: "imaps"
  imap_folder: "INBOX"
  polling_interval_ms: 10000

nlp:
  lemmatizer:
    implementation: external-api
    api-url: https://lindat.mff.cuni.cz/services/udpipe/api/process
    connectTimeoutMillis: 5000
    read-timeout-millis: 30000
  api:
    client:
      embedding-api-url: https://api-inference.huggingface.co/models/sentence-transformers/all-MiniLM-L6-v2
      apiKey: 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
      connection-timeout-millis: 5000
      read-timeout-millis: 30000
      max-batch-size: 50

answersearch:
  weights:
    similarity: 0.7
    trust: 0.3

ml:
  api:
    params:
      default-temperature: 0.7
      default-max-new-tokens: 250
      default-top-p: 0.9
      default-do-sample: true
      default-stream: false
      max-retries: 3
      retry-delay: 2s
      correction:
        temperature: 0.5
        max-new-tokens: 100
        is-text-generation: true
      rewrite:
        temperature: 0.75
        max-new-tokens: 300
        is-text-generation: true
      general-answer:
        temperature: 0.6
        max-new-tokens: 500
        is-text-generation: true

websocket:
  endpoint: /ws
  allowed-origins:
    #    - "http://localhost:3000"
    #    - "http://localhost:4200"
    - "*"
  heartbeat:
    interval: 30000
    timeout: 10000
  message:
    buffer-size: 16384
    send-timeout: 3000
  transport-message-size-limit: 131072
  stomp:
    simple-broker:
      enabled: true
      destination-prefixes:
        - /topic/
        - /queue/
    application-destination-prefix: /app
    user-destination-prefix: /user
  topics:
    company:
      pending-chats: /topic/company/{companyId}/chats/pending
      assigned-chats: /topic/company/{companyId}/chats/assigned
    chat:
      base: /topic/chat/{chatId}
      status: /status
      messages: /messages
      typing: /typing
      notifications: /notifications
    user:
      base: /user/{userId}/queue
      notifications: /notifications
      assigned-chats: /chats/assigned
      chat-closed: /chats/closed
    widget:
      base: /user/{widgetSessionId}/widget
      messages: /messages
      config: /config
      notifications: /notifications

  security:
    jwt:
      header-name: Authorization
      token-prefix: Bearer\
  broker:
    task-scheduler-pool-size: 2
    inbound-channel-core-pool-size: 4
    inbound-channel-max-pool-size: 8
    outbound-channel-core-pool-size: 4
    outbound-channel-max-pool-size: 8

subscription:
  price: 790
server:
  forward-headers-strategy: framework
