spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://postgres:5432/ans_machine_db
    username: postgres
    password: p855060123d
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  security:
    user:
      name: admin
      password: admin

validation:
  file-upload:
    max-file-size: 10MB
    allowed-file-types:
      - "image/png"
      - "image/jpeg"
      - "application/pdf"

file-upload:
  location: /uploads
  clamav-host: localhost
  clamav-port: 3310

server:
  error:
    include-stacktrace: never

jwt:
  secret: "sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3sgsVqPHW8JA36RhNDUD4b6V5u28BhzJX1rISYU2menKnwPTYy3"
  access-expiration: 100000
  refresh-expiration: 86400000

subscription:
  price: 790.00