spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ans_machine_db
    username: postgres
    password: nikita090504
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


validation:
  file-upload:
    max-file-size: 10MB
    allowed-file-types:
      - "image/png"
      - "image/jpeg"
      - "application/pdf"

file-upload:
  location: /uploads
  clamav-host: localhost
  clamav-port: 3310