name: DoTestAndDeploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.ServerSSH }}" > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
           cat ~/.ssh/id_ed25519
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 root@176.98.178.29 << 'EOF'
            cd TPProduct
            git pull
            docker-compose down
            docker-compose up --build -d
           EOF
